import {useEffect,useRef,useState,type CSSProperties,type FormEvent} from 'react';
import {UserRound,CalendarDays,LayoutDashboard,Backpack,Palette,Store,Plus,Coins,Sparkles,Flag,Search,GripVertical,Check,Shield,ArrowUpRight,X,Pencil} from 'lucide-react';
import {items,labels,presets,progression,reward,statuses,type Action,type State,type Task} from './domain';
import {storage} from './storage';
import CalendarPanel from './CalendarPanel';
import CharacterPanel,{WardrobeSummary} from './CharacterPanel';
import CharacterSprite from './CharacterSprite';
import {PixelMage,PixelScene,PixelRelic} from './FantasyArt';
type Page='board'|'inventory'|'shop'|'theme'|'calendar'|'character';
export default function App(){
 const [state,setState]=useState<State|null>(null),[page,setPage]=useState<Page>('board'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[editing,setEditing]=useState<Task|'new'|null>(null),[draftTheme,setDraftTheme]=useState<State['theme']|null>(null);
 const mutation=useRef(false);const dialog=useRef<HTMLDialogElement>(null);const drag=useRef<string|null>(null);
 useEffect(()=>{storage.load().then(setState).catch(()=>setError('Não foi possível carregar seu progresso. Seus dados foram preservados. Verifique o armazenamento e reinicie o app.'));},[]);
 useEffect(()=>{if(editing)dialog.current?.showModal();else dialog.current?.close();},[editing]);
 async function dispatch(action:Action){if(mutation.current)return false;mutation.current=true;setBusy(true);setError('');try{const result=await storage.dispatch(action);setState(result.state);setNotice(result.message);return true;}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar. Tente novamente.');return false;}finally{mutation.current=false;setBusy(false);}}
 if(!state)return <main className="loading"><Shield size={48}/><h1>QuestDesk</h1><p role="alert">{error||'Preparando sua jornada…'}</p></main>;
 const progress=progression(state.xp),theme=draftTheme??state.theme;
 const vars={'--bg':theme.background,'--surface':theme.surface,'--card':theme.card,'--accent':theme.accent,'--text':theme.text,'--radius':`${theme.radius}px`} as CSSProperties;
 const completed=state.tasks.filter(t=>t.status==='done').length;
 const filtered=state.tasks.filter(t=>(t.title+' '+t.description).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 function drop(event:React.DragEvent,status:Task['status'],beforeId?:string){event.preventDefault();event.stopPropagation();const id=drag.current;if(id&&!busy)void dispatch({type:'move',id,status,beforeId});drag.current=null;}
 async function saveTask(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const fields={title:String(data.get('title')).trim(),description:String(data.get('description')),schedule:data.get('date')?{date:String(data.get('date')),time:data.get('time')?String(data.get('time')):undefined,minutes:Number(data.get('minutes')||60)}:undefined,difficulty:String(data.get('difficulty')??(editing!=='new'&&editing?editing.difficulty:'easy')) as Task['difficulty']};const ok=await dispatch(editing==='new'?{type:'add',...fields}:{type:'edit',id:(editing as Task).id,...fields});if(ok)setEditing(null);}
 return <div className="app" style={vars}>
 <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('board');}}><div className="brand-mark"><Shield size={23}/></div><div>QuestDesk<small>CONQUISTE SEU DIA</small></div></a><div className="workspace-label">SEU ESPAÇO</div><nav>{([{id:'board',name:'Missões',icon:LayoutDashboard},{id:'character',name:'Personagem',icon:UserRound},{id:'calendar',name:'Calendário',icon:CalendarDays},{id:'inventory',name:'Inventário',icon:Backpack},{id:'shop',name:'Mercado',icon:Store},{id:'theme',name:'Aparência',icon:Palette}] as const).map(item=><button key={item.id} className={page===item.id?'nav active':'nav'} onClick={()=>{setPage(item.id);setDraftTheme(null);}}><item.icon size={19}/>{item.name}{item.id==='board'&&<span className="count">{state.tasks.filter(t=>t.status!=='done').length}</span>}</button>)}</nav>
 <div className="sidebar-bottom"><div className="journey"><Sparkles size={22}/><h3>Um passo por vez.</h3><p>Grandes conquistas começam com pequenas missões.</p></div><div className="profile"><div className="avatar"><CharacterSprite character={state.character} size={48}/></div><div>{state.character.name}<small>Nível {progress.level} · Iniciante</small></div><span className="online" title="Armazenamento local"/></div></div></aside>
 <main><header><span className="breadcrumb">Meu espaço <span>/</span> {page==='character'?'Personagem':page==='calendar'?'Calendário':page==='board'?'Quadro de missões':page==='inventory'?'Inventário':page==='shop'?'Mercado':'Aparência'}</span><div className="header-right"><span className="offline"><span className="online"/> {state.calendar.google?'Local · Google configurado':'Local · offline'}</span><span className="gold"><Coins size={17}/>{state.gold} <small>Gold</small></span></div></header>
 <div className="content"><section className={page==='calendar'?'page-title calendar-banner':'page-title'}><PixelScene/><div className="hero-content"><div className="eyebrow">✦ SEU DIÁRIO DE AVENTURAS</div><h1>{page==='character'?'Uma jornada com a sua cara.':page==='calendar'?'Dê tempo às suas conquistas.':page==='board'?'Sua próxima grande aventura.':page==='inventory'?'Tesouros da sua jornada.':page==='shop'?'Dê valor ao seu progresso.':'Um espaço com a sua cara.'}</h1><p>{page==='character'?'Crie seu aventureiro e vista as conquistas das suas missões.':page==='calendar'?'Planeje suas missões e consulte seus compromissos no mesmo lugar.':page==='board'?'Pequenas missões. Novos tesouros. Um pouco mais de magia no seu dia.':page==='inventory'?'Sua coleção cresce a cada descoberta. Os itens desta versão são cosméticos.':page==='shop'?'Troque o Gold das suas missões por itens para sua coleção.':'Personalize as cores e os detalhes do seu painel.'}</p></div><div className="hero-mage"><CharacterSprite character={state.character} size={128}/></div></section>
 {page!=='calendar'&&page!=='character'&&<section className="stats"><div className="stat level"><div className="level-badge"><Shield size={46}/><b>{progress.level}</b></div><div className="level-content"><div className="stat-label">SEU NÍVEL <span>Aventureiro</span></div><strong>Nível {progress.level}</strong><div className="progress" role="progressbar" aria-label="Experiência do nível" aria-valuemin={0} aria-valuemax={progress.goal} aria-valuenow={progress.current}><i style={{width:`${100*progress.current/progress.goal}%`}}/></div><small>{progress.current} / {progress.goal} EXP para o próximo nível</small></div></div><div className="stat"><span className="stat-label"><Flag size={17}/> MISSÕES CONCLUÍDAS</span><strong>{completed.toString().padStart(2,'0')}</strong><small>de {state.tasks.length} missões no quadro</small></div><div className="stat"><span className="stat-label"><Coins size={17}/> SEU TESOURO</span><strong className="gold-text">{state.gold}<small> Gold</small></strong><small>Transforme dedicação em recompensas</small></div></section>}
 {error&&<div className="error" role="alert">{error}</div>}
 <div className="notice" role="status" aria-live="polite">{notice||'Seu progresso é salvo neste dispositivo.'}</div>
 {page==='character'&&<CharacterPanel state={state} busy={busy} dispatch={dispatch}/>}
 {page==='calendar'&&<CalendarPanel state={state} busy={busy} dispatch={dispatch} edit={setEditing} newTask={()=>setEditing('new')}/>}
 {page==='board'&&<><div className="toolbar"><div><h2>Quadro de missões <span className="pill">{state.tasks.length}</span></h2><p>Arraste os cards ou use o seletor de status.</p></div><div className="actions"><label className="search"><Search size={17}/><input aria-label="Buscar missões" placeholder="Buscar missão…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="primary" onClick={()=>setEditing('new')} disabled={busy}><Plus size={17}/> Nova missão</button></div></div>
 <div className="kanban">{statuses.map(status=><section className={`column ${status}`} key={status} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,status)} aria-label={labels[status]}><div className="column-head"><h3><i/>{labels[status]} <span>{filtered.filter(t=>t.status===status).length}</span></h3><span className="column-symbol">{status==='done'?<Check size={15}/>:status==='doing'?<Sparkles size={15}/>:<Flag size={15}/>}</span></div><div className="cards">{filtered.filter(t=>t.status===status).map(task=><article className="task" key={task.id} draggable={!busy&&!query} onDragStart={e=>{drag.current=task.id;e.dataTransfer.setData('text/plain',task.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>{drag.current=null;}} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,status,task.id)}><div className="task-top"><span className={`difficulty ${task.difficulty}`}>{reward[task.difficulty].label}</span><div className="task-tools"><button title="Editar missão" aria-label={`Editar ${task.title}`} onClick={()=>setEditing(task)}><Pencil size={14}/></button><GripVertical size={16}/></div></div><h4>{task.title}</h4>{task.description&&<p>{task.description}</p>}{task.schedule&&<p className="task-date"><CalendarDays size={12}/> {task.schedule.date.split('-').reverse().join('/')}{task.schedule.time?` · ${task.schedule.time}`:' · Dia inteiro'}</p>}<div className="task-rewards"><span><Sparkles size={13}/> {reward[task.difficulty].xp} EXP</span><span><Coins size={13}/> {reward[task.difficulty].gold} Gold</span></div><div className="task-footer"><select disabled={busy} aria-label={`Status de ${task.title}`} value={task.status} onChange={e=>void dispatch({type:'move',id:task.id,status:e.target.value as Task['status']})}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select>{task.rewarded&&<span title="Recompensa já recebida" className="received"><Check size={12}/> Recebida</span>}</div></article>)}{!filtered.some(t=>t.status===status)&&<div className="empty-column"><Flag size={24}/><p>{status==='done'?'Sua próxima conquista vai aparecer aqui.':'Solte uma missão aqui.'}</p></div>}</div></section>)}</div><div className="board-tip"><Sparkles size={16}/><span>Uma missão concluída pode revelar um novo cosmético. Chance de drop: <b>30%</b>.</span><span>SEM PRESSA. COM PROPÓSITO.</span></div></>}
 {(page==='inventory'||page==='shop')&&<>{page==='inventory'&&<WardrobeSummary state={state} open={()=>setPage('character')}/>}<div className="toolbar"><h2>{page==='inventory'?'Sua coleção':'Relíquias disponíveis'}</h2><span className="muted">Comum · Raro · Épico</span></div><div className="item-grid">{items.map(item=>{const qty=state.inventory.find(i=>i.id===item.id)?.quantity??0;return <article className="item" key={item.id}><span className="rarity" style={{color:item.color}}>{item.rarity}</span><PixelRelic id={item.id} size={120}/><h3>{item.name}</h3><p>{page==='inventory'?qty?`${qty} na sua coleção`:'Ainda não descoberto':'Item cosmético · sem bônus de EXP'}</p>{page==='shop'?<button disabled={busy||state.gold<item.price} className="secondary" onClick={()=>void dispatch({type:'buy',id:item.id})}><Coins size={15}/>{item.price} Gold <ArrowUpRight size={16}/></button>:<span className="pill">{qty?'Adquirido':'Conclua missões ou visite o mercado'}</span>}</article>;})}</div></>}
 {page==='theme'&&<section className="theme-panel"><h2>Escolha seu ambiente</h2><div className="presets">{Object.entries(presets).map(([key,preset])=><button className="secondary" key={key} onClick={()=>setDraftTheme({...preset})}><span className="swatch" style={{background:preset.accent}}/>{key==='guild'?'Aurora Arcana':key==='forest'?'Bosque Feérico':'Crepúsculo Astral'}</button>)}</div><h3>Ajuste cada detalhe</h3><div className="color-grid">{([{key:'background',name:'Fundo do aplicativo'},{key:'surface',name:'Painéis e barra lateral'},{key:'card',name:'Cards e campos'},{key:'accent',name:'Destaques'},{key:'text',name:'Texto principal'}] as const).map(field=><label key={field.key}>{field.name}<input type="color" value={theme[field.key]} onChange={e=>setDraftTheme({...theme,[field.key]:e.target.value})}/></label>)}<label>Cantos dos cards: {theme.radius}px<input type="range" min="0" max="24" value={theme.radius} onChange={e=>setDraftTheme({...theme,radius:Number(e.target.value)})}/></label></div><p className="muted">Prévia ao vivo. Preserve o contraste entre texto e fundo para facilitar a leitura.</p><div className="actions"><button className="primary" disabled={busy||!draftTheme} onClick={async()=>{if(await dispatch({type:'theme',theme}))setDraftTheme(null);}}>Salvar aparência</button><button className="secondary" onClick={()=>setDraftTheme(null)}>Descartar prévia</button></div></section>}
 <footer>QUESTDESK <span>Fantasia pixel · versão 0.4</span></footer></div></main>
 <dialog ref={dialog} onCancel={()=>setEditing(null)} onClose={()=>setEditing(null)}><form onSubmit={saveTask} key={typeof editing==='object'?editing?.id:'new'}><div className="modal-heading"><h2>{editing==='new'?'Nova missão':'Editar missão'}</h2><button type="button" aria-label="Fechar" onClick={()=>setEditing(null)}><X size={22}/></button></div>{error&&<p className="error" role="alert">{error}</p>}<label>O que você vai conquistar?<input name="title" required maxLength={120} autoFocus defaultValue={editing&&editing!=='new'?editing.title:''} placeholder="Ex.: finalizar o conceito do personagem"/></label><label>Detalhes<textarea name="description" maxLength={2000} rows={4} defaultValue={editing&&editing!=='new'?editing.description:''}/></label><fieldset className="schedule-fields"><legend>Agendamento opcional</legend><label>Data<input type="date" name="date" defaultValue={editing&&editing!=='new'?editing.schedule?.date??'':''}/></label><label>Horário<input type="time" name="time" defaultValue={editing&&editing!=='new'?editing.schedule?.time??'':''}/></label><label>Duração (minutos)<input type="number" min="15" max="1440" step="1" name="minutes" defaultValue={editing&&editing!=='new'?editing.schedule?.minutes??60:60}/></label><small>Sem horário: dia inteiro. Limpe a data para retirar do calendário.</small></fieldset><label>Esforço estimado<select name="difficulty" defaultValue={editing&&editing!=='new'?editing.difficulty:'medium'} disabled={editing!=='new'&&!!editing?.rewarded}>{Object.entries(reward).map(([key,r])=><option key={key} value={key}>{r.label} · {r.xp} EXP · {r.gold} Gold</option>)}</select></label><p className="muted">Recompensas são concedidas somente na primeira conclusão.</p><button className="primary" disabled={busy} type="submit">{busy?'Salvando…':'Salvar missão'}</button></form></dialog>
 </div>;
}
