import {useRef,useState,type DragEvent,type FormEvent} from 'react';
import {CalendarDays,Check,Coins,Flag,GripVertical,MoreHorizontal,Pencil,Plus,Search,Sparkles,Trash2,X} from 'lucide-react';
import {reward,type Action,type State,type Task} from './domain';

type Props={state:State;busy:boolean;dispatch:(action:Action)=>Promise<boolean>;edit:(task:Task)=>void;newTask:(columnId:string)=>void};
export default function BoardPanel({state,busy,dispatch,edit,newTask}:Props){
 const [query,setQuery]=useState(''),[renaming,setRenaming]=useState<string|null>(null),[adding,setAdding]=useState(false),[draft,setDraft]=useState(''),[hover,setHover]=useState<string|null>(null);
 const draggedTask=useRef<string|null>(null),draggedColumn=useRef<string|null>(null);
 const columns=state.columns,filtered=state.tasks.filter(t=>(t.title+' '+t.description).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const title=(id:string)=>columns.find(c=>c.id===id)?.title??'Etapa';
 async function saveColumn(event:FormEvent,id?:string){event.preventDefault();const value=draft.trim();if(!value)return;const ok=await dispatch(id?{type:'columnRename',id,title:value}:{type:'columnAdd',title:value});if(ok){setDraft('');setRenaming(null);setAdding(false);}}
 function moveTask(event:DragEvent,status:string,beforeId?:string){event.preventDefault();event.stopPropagation();const id=draggedTask.current;draggedTask.current=null;setHover(null);if(id&&!busy&&id!==beforeId)void dispatch({type:'move',id,status,beforeId});}
 function moveColumn(event:DragEvent,beforeId:string){if(!draggedColumn.current)return;event.preventDefault();event.stopPropagation();const id=draggedColumn.current;draggedColumn.current=null;setHover(null);if(id!==beforeId&&!busy)void dispatch({type:'columnMove',id,beforeId});}
 return <>
  <div className="toolbar board-toolbar"><div><h2>Quadro de missões <span className="pill">{state.tasks.length}</span></h2><p>Organize suas etapas, arraste os cards e conclua missões para receber recompensas.</p></div><div className="actions"><label className="search"><Search size={17}/><input aria-label="Buscar missões" placeholder="Buscar missão…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="primary" onClick={()=>newTask('todo')} disabled={busy}><Plus size={17}/> Nova missão</button></div></div>
  <div className="kanban" aria-label="Quadro Kanban de missões">
   {columns.map((column,index)=>{const tasks=filtered.filter(t=>t.status===column.id),all=state.tasks.filter(t=>t.status===column.id);return <section className={`column ${column.id==='done'?'done':column.id==='doing'?'doing':''} ${hover===`column:${column.id}`?'column-over':''}`} key={column.id} aria-label={column.title} onDragOver={e=>{e.preventDefault();if(draggedColumn.current)setHover(`column:${column.id}`);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setHover(null);}} onDrop={e=>draggedColumn.current?moveColumn(e,column.id):moveTask(e,column.id)}>
    <div className="column-head"><div className="column-title"><i/>{renaming===column.id?<form onSubmit={e=>void saveColumn(e,column.id)} className="column-name-form"><input aria-label="Nome da etapa" autoFocus maxLength={40} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setRenaming(null);}} onBlur={e=>{if(!e.currentTarget.form?.contains(e.relatedTarget as Node))setRenaming(null);}}/><button title="Salvar nome" disabled={busy||!draft.trim()}><Check size={15}/></button></form>:<strong title={column.title} onDoubleClick={()=>{setDraft(column.title);setRenaming(column.id);}}>{column.title}</strong>}<span className="column-count">{tasks.length}</span></div><div className="column-actions"><button className="column-grip" draggable={!busy&&!query} onDragStart={e=>{draggedColumn.current=column.id;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',`column:${column.id}`);}} onDragEnd={()=>{draggedColumn.current=null;setHover(null);}} aria-label={`Arrastar etapa ${column.title}`} title="Arraste para reordenar"><GripVertical size={16}/></button><details><summary aria-label={`Opções da etapa ${column.title}`} title="Opções da etapa"><MoreHorizontal size={19}/></summary><div className="column-menu"><button onClick={e=>{setDraft(column.title);setRenaming(column.id);e.currentTarget.closest('details')?.removeAttribute('open');}}><Pencil size={14}/> Renomear</button><button disabled={busy||index===0} onClick={()=>void dispatch({type:'columnMove',id:column.id,beforeId:columns[index-1].id})}>Mover para esquerda</button><button disabled={busy||index===columns.length-1} onClick={()=>void dispatch({type:'columnMove',id:column.id,beforeId:columns[index+2]?.id})}>Mover para direita</button>{!['todo','doing','done'].includes(column.id)&&<button className="danger" disabled={busy||all.length>0} title={all.length?'Mova os cards antes de remover a etapa':''} onClick={()=>void dispatch({type:'columnRemove',id:column.id})}><Trash2 size={14}/> Remover etapa</button>}</div></details></div></div>
    <div className="cards">{tasks.map(task=><article className={`task ${hover===`task:${task.id}`?'task-over':''}`} key={task.id} draggable={!busy&&!query} onDragStart={e=>{draggedTask.current=task.id;e.dataTransfer.setData('text/plain',task.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>{draggedTask.current=null;setHover(null);}} onDragOver={e=>{e.preventDefault();e.stopPropagation();if(draggedTask.current)setHover(`task:${task.id}`);}} onDrop={e=>draggedColumn.current?moveColumn(e,column.id):moveTask(e,column.id,task.id)}><div className="task-top"><span className={`difficulty ${task.difficulty}`}>{reward[task.difficulty].label}</span><div className="task-tools"><button title="Editar missão" aria-label={`Editar ${task.title}`} onClick={()=>edit(task)}><Pencil size={14}/></button><GripVertical size={16}/></div></div><h4>{task.title}</h4>{task.description&&<p>{task.description}</p>}{task.schedule&&<p className="task-date"><CalendarDays size={12}/> {task.schedule.date.split('-').reverse().join('/')}{task.schedule.time?` · ${task.schedule.time}`:' · Dia inteiro'}</p>}<div className="task-rewards"><span><Sparkles size={13}/> {reward[task.difficulty].xp} EXP</span><span><Coins size={13}/> {reward[task.difficulty].gold} Gold</span></div><div className="task-footer"><select disabled={busy} aria-label={`Etapa de ${task.title}`} value={task.status} onChange={e=>void dispatch({type:'move',id:task.id,status:e.target.value})}>{columns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>{task.rewarded&&<span title="Recompensa já recebida" className="received"><Check size={12}/> Recebida</span>}</div></article>)}{!tasks.length&&<div className="empty-column"><Flag size={24}/><p>{query?'Nenhuma missão encontrada nesta etapa.':column.id==='done'?'Sua próxima conquista vai aparecer aqui.':'Solte uma missão aqui.'}</p></div>}</div>
    {column.id!=='done'&&<button className="add-card" onClick={()=>newTask(column.id)} disabled={busy}><Plus size={15}/> Adicionar missão</button>}
   </section>;})}
   {columns.length<12&&<div className="new-column">{adding?<form onSubmit={e=>void saveColumn(e)}><input aria-label="Nome da nova etapa" autoFocus maxLength={40} placeholder="Nome da etapa" value={draft} onChange={e=>setDraft(e.target.value)}/><div><button className="primary" disabled={busy||!draft.trim()}>Criar etapa</button><button className="icon-button" type="button" aria-label="Cancelar" onClick={()=>{setAdding(false);setDraft('');}}><X size={18}/></button></div></form>:<button onClick={()=>{setAdding(true);setDraft('');}}><Plus size={17}/> Adicionar etapa</button>}</div>}
  </div>
  <div className="board-tip"><Sparkles size={16}/><span>Concluir uma missão na etapa <b>{title('done')}</b> concede EXP e Gold uma única vez. Chance de drop: <b>30%</b>.</span><span>SEM PRESSA. COM PROPÓSITO.</span></div>
 </>;
}
