import {useMemo,useRef,useState} from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import listPlugin from '@fullcalendar/list';
import interactionPlugin from '@fullcalendar/interaction';
import googleCalendarPlugin from '@fullcalendar/google-calendar';
import ptBr from '@fullcalendar/core/locales/pt-br';
import type {EventSourceInput,EventChangeArg,EventClickArg} from '@fullcalendar/core';
import {CalendarDays,Download,Upload,RefreshCw} from 'lucide-react';
import {type State,type Task,type Action} from './domain';
import {downloadICS,importEvents,parseCalendar,taskEvent,scheduleFromEvent} from './calendar-io';
export default function CalendarPanel({state,busy,dispatch,edit,newTask}:{state:State;busy:boolean;dispatch:(action:Action)=>Promise<boolean>;edit:(task:Task)=>void;newTask:()=>void}){
 const calendar=useRef<FullCalendar>(null),file=useRef<HTMLInputElement>(null);
 const [error,setError]=useState(''),[info,setInfo]=useState(''),[loading,setLoading]=useState(false),[googleStatus,setGoogleStatus]=useState('');
 const [detail,setDetail]=useState<{title:string;origin:string;description:string}|null>(null);
 const events=useMemo(()=>state.tasks.flatMap(t=>{const e=taskEvent(t);return e?[e]:[];}),[state.tasks]);
 const sources=useMemo<EventSourceInput[]>(()=>[
 ...state.calendar.imports.map(source=>({id:source.id,events:((range,success,failure)=>{try{success(importEvents(source.text,source.id,source.name,range.start,range.end));}catch(e){setError(`Agenda ${source.name}: ${e instanceof Error?e.message:'Erro de leitura.'}`);failure(new Error('Falha ao ler arquivo importado.'));}}) as Exclude<import('@fullcalendar/core').EventSourceFunc,undefined>})),
 ...(state.calendar.google?[{id:'google',googleCalendarId:state.calendar.google.calendarId,googleCalendarApiKey:state.calendar.google.apiKey,editable:false,color:'#e9c68f',textColor:'#241a27',success:()=>{setGoogleStatus('Agenda pública atualizada.');},failure:()=>{setGoogleStatus('Não foi possível ler o Google. Verifique conexão, ID, chave e acesso público.');},eventDataTransform:(event:Record<string,unknown>)=>({...event,id:`google:${event.id}`,url:undefined,extendedProps:{origin:'Google Calendar'}})}]:[])
 ],[state.calendar.imports,state.calendar.google]);
 async function change(arg:EventChangeArg){const taskId=arg.event.extendedProps.taskId;if(!taskId||!arg.event.start||busy){arg.revert();return;}const ok=await dispatch({type:'schedule',id:taskId,schedule:scheduleFromEvent(arg.event.start,arg.event.allDay,arg.event.end)});if(!ok)arg.revert();}
 function click(arg:EventClickArg){arg.jsEvent.preventDefault();const task=state.tasks.find(t=>t.id===arg.event.extendedProps.taskId);if(task)edit(task);else setDetail({title:arg.event.title,origin:String(arg.event.extendedProps.origin||'Agenda externa'),description:String(arg.event.extendedProps.description||'Evento externo somente para consulta.')});}
 async function importFile(selected:File){setError('');setInfo('');try{if(selected.size>1000000)throw Error('O arquivo deve ter até 1 MB.');const text=await selected.text();parseCalendar(text);const now=new Date();importEvents(text,'preview',selected.name,new Date(now.getFullYear(),now.getMonth(),1),new Date(now.getFullYear(),now.getMonth()+1,1));const ok=await dispatch({type:'calendarImport',source:{id:crypto.randomUUID(),name:selected.name.slice(0,100),text}});if(ok)setInfo('Arquivo importado como cópia local. Para atualizar, remova esta cópia e importe novamente.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível importar esta agenda.');}finally{if(file.current)file.current.value='';}}
 return <section className="calendar-area"><div className="toolbar"><div><h2><CalendarDays size={22}/> Calendário de missões</h2><p>Clique em uma missão para editar. Arraste para reagendar.</p></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>file.current?.click()}><Upload size={15}/> Importar .ics</button><button className="secondary" disabled={!events.length} onClick={()=>downloadICS(state.tasks)}><Download size={15}/> Exportar missões</button><button className="primary" disabled={busy} onClick={newTask}>Nova missão</button></div></div>
 <input ref={file} type="file" accept=".ics,text/calendar" aria-label="Arquivo de agenda" hidden onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);}}/>
 {error&&<p className="error" role="alert">{error}</p>}{info&&<p className="muted" role="status">{info}</p>}
 <div className="calendar-legend"><span>✦ Missões locais</span><span>◆ Arquivos importados</span><span>◆ Google público</span><small>Fuso: {Intl.DateTimeFormat().resolvedOptions().timeZone} · {loading?'Atualizando…':'Eventos externos não concedem EXP ou Gold.'}</small></div>
 <div className="calendar-surface"><FullCalendar ref={calendar} plugins={[dayGridPlugin,timeGridPlugin,listPlugin,interactionPlugin,googleCalendarPlugin]} locale={ptBr} initialView="dayGridMonth" headerToolbar={{left:'prev,next today',center:'title',right:'dayGridMonth,timeGridWeek,listWeek'}} buttonIcons={false} stickyHeaderDates={false} buttonText={{prev:'‹',next:'›',today:'Hoje',month:'Mês',week:'Semana',list:'Lista'}} height="auto" events={events} eventSources={sources} editable={!busy} eventDurationEditable={false} eventStartEditable={!busy} eventClick={click} eventDrop={change} loading={setLoading} dayMaxEvents={3} firstDay={1} nowIndicator timeZone="local" eventTimeFormat={{hour:'2-digit',minute:'2-digit',hour12:false}} slotLabelFormat={{hour:'2-digit',minute:'2-digit',hour12:false}} slotMinTime="06:00:00" slotMaxTime="24:00:00"/></div>
 {detail&&<div className="external-detail" role="status"><strong>{detail.title}</strong><p>{detail.origin} · Somente leitura</p><p>{detail.description}</p><button className="secondary" onClick={()=>setDetail(null)}>Fechar detalhes</button></div>}
 <div className="calendar-bottom"><section className="calendar-box"><h3>Missões sem data <span className="pill">{state.tasks.filter(t=>!t.schedule).length}</span></h3><p className="muted">Abra uma missão e defina uma data para ela aparecer no calendário.</p><div className="unscheduled">{state.tasks.filter(t=>!t.schedule).map(t=><button disabled={busy} key={t.id} onClick={()=>edit(t)}>{t.title}<span>Agendar →</span></button>)}</div></section>
 <section className="calendar-box"><h3>Agendas externas</h3><p className="muted">Importe arquivos .ics do Google Calendar, Outlook, Apple Calendar e outros serviços. A importação é uma cópia, sem sincronização automática.</p>{state.calendar.imports.map(s=><div className="imported-source" key={s.id}><span>{s.name}</span><button className="secondary" disabled={busy} onClick={()=>void dispatch({type:'calendarRemove',id:s.id})}>Remover cópia</button></div>)}
 <details><summary>Google Calendar público · somente leitura</summary><p className="muted">Use apenas uma agenda que já seja pública. Agendas privadas precisarão de conexão OAuth em uma próxima etapa.</p><form className="google-form" key={state.calendar.google?.calendarId??'disconnected'} onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setGoogleStatus('Consultando agenda pública…');await dispatch({type:'googleCalendar',google:{calendarId:String(data.get('calendarId')).trim(),apiKey:String(data.get('apiKey')).trim()}});}}><label>ID da agenda pública<input name="calendarId" required maxLength={300} defaultValue={state.calendar.google?.calendarId??''} placeholder="…@group.calendar.google.com"/></label><label>Chave da Google Calendar API<input name="apiKey" type="password" autoComplete="off" required maxLength={250} defaultValue={state.calendar.google?.apiKey??''}/></label><p className="muted">A chave fica salva neste dispositivo e é enviada ao Google ao consultar a agenda. Não insira senha da conta nem segredo OAuth.</p><div className="actions"><button className="primary" disabled={busy} type="submit">Carregar agenda pública</button>{state.calendar.google&&<button className="secondary" type="button" disabled={busy} onClick={async()=>{if(await dispatch({type:'googleCalendar',google:undefined}))setGoogleStatus('');}}>Desconectar</button>}</div></form></details>
 {state.calendar.google&&<button className="secondary refresh-calendar" onClick={()=>{setGoogleStatus('Atualizando…');calendar.current?.getApi().refetchEvents();}}><RefreshCw size={14}/> Atualizar agendas</button>}{googleStatus&&<p className="muted" role="status">{googleStatus}</p>}
 </section></div></section>;
}
