import {useEffect,useState} from 'react';
import {Shirt,Lock,Check,Sparkles,RotateCw,Play,Pause} from 'lucide-react';
import CharacterSprite from './CharacterSprite';
import {cosmetics,slots,bodies,skinLabels,hairColors,hairStyles,rarityLabels,fits,normalizeCharacter,type Character,type Slot} from './character-model';
import type {State,Action} from './domain';
export function WardrobeSummary({state,open}:{state:State;open:()=>void}){return <section className="wardrobe-summary"><div><h2>Guarda-roupa do aventureiro</h2><p>{state.wardrobe.length} de {cosmetics.length} peças desbloqueadas. Equipe seus prêmios na página Personagem.</p></div><button className="primary" onClick={open}><Shirt size={16}/> Abrir personagem</button></section>;}
export default function CharacterPanel({state,busy,dispatch}:{state:State;busy:boolean;dispatch:(action:Action)=>Promise<boolean>}){
 const [draft,setDraft]=useState<Character>(state.character),[slot,setSlot]=useState<Slot>('outfit'),[direction,setDirection]=useState(2),[walking,setWalking]=useState(false),[tryOn,setTryOn]=useState<string|null>(null),[credits,setCredits]=useState<{filename:string;authors:string;licenses:string;selectedLicense:string;urls:string}[]|null>(null),[creditError,setCreditError]=useState('');
 useEffect(()=>{setDraft(state.character);setTryOn(null);},[state.character]);
 const base=normalizeCharacter(draft,state.wardrobe);const item=cosmetics.find(i=>i.id===tryOn);const preview=item&&fits(item,base.body)?{...base,equipment:{...base.equipment,[item.slot]:item.id}}:base;
 const dirty=['name','body','skin','hair','hairColor'].some(key=>draft[key as keyof Character]!==state.character[key as keyof Character]);
 const candidates=cosmetics.filter(i=>i.slot===slot&&fits(i,base.body));
 const compatibleTotal=cosmetics.filter(i=>fits(i,base.body)).length;const acquired=cosmetics.filter(i=>fits(i,base.body)&&state.wardrobe.includes(i.id)).length;
 async function loadCredits(){if(credits)return;try{const response=await fetch('./lpc/credits.json');if(!response.ok)throw Error();const json=await response.json();setCredits(json.assets);}catch{setCreditError('Não foi possível abrir os créditos. Eles também estão em public/lpc/credits.json no projeto.');}}
 return <section className="character-page"><div className="toolbar"><div><h2><Shirt size={21}/> Seu aventureiro</h2><p>Sua identidade é livre. Seus equipamentos contam sua jornada.</p></div><span className="pill">{state.wardrobe.length}/{cosmetics.length} peças na coleção</span></div><div className="character-layout"><aside className="character-preview"><div className="character-stage"><div className="stage-spark">✦</div><CharacterSprite character={preview} size={256} direction={direction} animate={walking}/><div className="stage-platform"/></div><h2>{draft.name||'Seu aventureiro'}</h2><p className="muted">{bodies[base.body]} · {acquired}/{compatibleTotal} peças compatíveis</p><div className="actions"><button className="secondary" aria-label="Girar personagem" onClick={()=>setDirection((direction+1)%4)}><RotateCw size={15}/> Girar</button><button className="secondary" onClick={()=>setWalking(!walking)}>{walking?<Pause size={15}/>:<Play size={15}/>} {walking?'Pausar':'Andar'}</button></div>{item&&<div className="try-on"><strong>Provando: {item.name}</strong><p>{state.wardrobe.includes(item.id)?'Peça da sua coleção.':'Prévia de uma peça bloqueada. Conclua missões para conquistá-la.'}</p><button className="secondary" onClick={()=>setTryOn(null)}>Voltar ao equipado</button></div>}<div className="equipped-list"><h3>Equipado</h3>{(Object.keys(slots) as Slot[]).map(s=><div key={s}><span>{slots[s]}</span><strong>{cosmetics.find(i=>i.id===state.character.equipment[s])?.name??'Nenhum'}</strong>{['head','back','feet'].includes(s)&&state.character.equipment[s]&&<button disabled={busy} aria-label={`Remover ${slots[s]}`} onClick={()=>void dispatch({type:'unequip',slot:s as 'head'|'back'|'feet'})}>×</button>}</div>)}</div></aside>
 <div className="character-controls"><form className="appearance-form" onSubmit={async e=>{e.preventDefault();const {equipment,...appearance}=base;await dispatch({type:'character',appearance});}}><h3>Aparência inicial <span className="pill">Sempre gratuita</span></h3><div className="appearance-grid"><label>Nome<input maxLength={30} required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Base<select aria-label="Base" value={draft.body} onChange={e=>{setDraft(normalizeCharacter({...draft,body:e.target.value as Character['body']},state.wardrobe));setTryOn(null);}}>{Object.entries(bodies).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Tom de pele<select aria-label="Tom de pele" value={draft.skin} onChange={e=>setDraft({...draft,skin:e.target.value as Character['skin']})}>{Object.entries(skinLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Cabelo<select aria-label="Cabelo" value={base.hair} onChange={e=>setDraft({...draft,hair:e.target.value as Character['hair']})}>{Object.entries(hairStyles).filter(([k])=>base.body==='child'?k==='wavy':k!=='wavy').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Cor do cabelo<select aria-label="Cor do cabelo" value={draft.hairColor} onChange={e=>setDraft({...draft,hairColor:e.target.value as Character['hairColor']})}>{Object.entries(hairColors).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div className="appearance-submit"><button className="primary" disabled={busy||!dirty}>Salvar aparência</button><button type="button" className="secondary" disabled={!dirty} onClick={()=>{setDraft(state.character);setTryOn(null);}}>Descartar</button></div></div><p className="muted">A base infantil tem um conjunto menor de peças. Trocar de base preserva toda a coleção e ajusta os itens equipados para versões compatíveis.</p></form>
 <section className="cosmetic-browser"><div className="cosmetic-heading"><h3>Ateliê de equipamentos</h3><span className="muted">30% de chance de drop por missão</span></div><div className="slot-tabs" role="group" aria-label="Categoria de equipamento">{(Object.keys(slots) as Slot[]).map(s=><button className={s===slot?'active':''} key={s} onClick={()=>setSlot(s)}>{slots[s]}</button>)}</div>{dirty&&<p className="muted">Salve a aparência antes de equipar peças.</p>}<div className="cosmetic-grid">{candidates.map(i=>{const owned=state.wardrobe.includes(i.id),equipped=state.character.equipment[i.slot]===i.id;const look={...base,equipment:{...base.equipment,[i.slot]:i.id}};return <article className={`cosmetic-card ${i.rarity}`} key={i.id}><span className="rarity">{i.starter?'Inicial':rarityLabels[i.rarity]}</span><button className="cosmetic-art" aria-label={`Experimentar ${i.name}`} onClick={()=>setTryOn(i.id)}><CharacterSprite character={look} size={96}/></button><h4>{i.name}</h4><span className="ownership">{equipped?<><Check size={12}/> Equipado</>:owned?'Na coleção':<><Lock size={12}/> Não obtido</>}</span><button className={owned?'primary':'secondary'} disabled={busy||owned&&(equipped||dirty)} onClick={()=>owned?void dispatch({type:'equip',id:i.id}):setTryOn(i.id)}>{owned?equipped?'Equipado':'Equipar':'Experimentar'}</button></article>;})}</div>{!candidates.length&&<p className="empty-category">Nenhuma peça desta categoria disponível para a base {bodies[base.body].toLowerCase()} neste pacote.</p>}<p className="drop-help"><Sparkles size={15}/> Drops priorizam peças novas compatíveis. Coleção completa: o drop vira 20 Gold. Reabrir a mesma missão não sorteia novamente.</p></section>
 </div></div><details className="lpc-credits" onToggle={e=>{if(e.currentTarget.open)void loadCredits();}}><summary>Créditos da arte · Universal LPC</summary><p>Sprites da comunidade Liberated Pixel Cup. Conjunto selecionado do Universal LPC Spritesheet Character Generator. Licenças selecionadas por peça: CC0, CC BY 3.0 ou CC BY-SA 3.0. As prévias combinam camadas e aplicam as paletas do acervo; o código do gerador não foi incorporado.</p><p>Origem: https://github.com/LiberatedPixelCup/Universal-LPC-Spritesheet-Character-Generator · Licença: https://creativecommons.org/licenses/by-sa/3.0/</p>{creditError&&<p role="alert">{creditError}</p>}{!credits&&!creditError&&<p>Carregando créditos…</p>}{credits?.map(c=><div key={c.filename}><strong>{c.filename}</strong><p>Autores: {c.authors}</p><p>Licença selecionada: {c.selectedLicense}. Alternativas oferecidas: {c.licenses}</p><p>Fontes: {c.urls}</p></div>)}</details></section>;
}
